### PR TITLE
Remove archetypes which are now in https://github.com/vaadin/archetypes

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/maven-integration/6)

### CODE REVIEW

**Comment by Artur-** [comment]
Review status: 0 of 207 files reviewed at latest revision, 1 unresolved discussion.

---

_[a discussion](https://reviewable.io:443/reviews/vaadin/maven-integration/6#-KTxrcpz_1GgWy6K_OJe:-KTxrcpz_1GgWy6K_OJf:b-ly3zfe) (no related file):_
There mig be some build changes that need to take place before this, @hesara  ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-integration/6)_

**Comment by Legioth** [comment]
What's the status of this? Are we still waiting for some build changes?

**Comment by hesara** [comment]
Reviewed 206 of 207 files at r1.
Review status: 206 of 207 files reviewed at latest revision, 2 unresolved discussions.

---

_[a discussion](https://reviewable.io:443/reviews/vaadin/maven-integration/6#-KTxrcpz_1GgWy6K_OJe:-KV9FOg5EwG1kg6ZU1FR:b-bhkk44) (no related file):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> There mig be some build changes that need to take place before this, @hesara  ?
> </details>
> Build changes done for 7.7 and master

---

_[test_archetypes.sh, line 1 at r1](https://reviewable.io:443/reviews/vaadin/maven-integration/6#-KV9FVm-AuZxx9ljX3Fn:-KV9FVm-AuZxx9ljX3Fo:b-arxog1) ([raw file](https://github.com/vaadin/maven-integration/blob/017f45dd9bb2b8141fb015042f711477328b8b73/test_archetypes.sh#L1)):_

> ``` Shell
> #!/bin/bash
> ```

is this script now anywhere else for e.g. easier testing of 7.7 branch builds, or obsolete/broken or something else?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-integration/6)_

**Comment by Artur-** [comment]
Review status: 206 of 207 files reviewed at latest revision, 1 unresolved discussion.

---

_[test_archetypes.sh, line 1 at r1](https://reviewable.io:443/reviews/vaadin/maven-integration/6#-KV9FVm-AuZxx9ljX3Fn:-KV9GlXaVdlhY20gQcP-:b-tn5rbn) ([raw file](https://github.com/vaadin/maven-integration/blob/017f45dd9bb2b8141fb015042f711477328b8b73/test_archetypes.sh#L1)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> is this script now anywhere else for e.g. easier testing of 7.7 branch builds, or obsolete/broken or something else?
> </details>
> It is currently nowhere. If it is needed, it must be added somewhere

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-integration/6)_

**Comment by hesara** [comment]
Reviewed 1 of 207 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[test_archetypes.sh, line 1 at r1](https://reviewable.io:443/reviews/vaadin/maven-integration/6#-KV9FVm-AuZxx9ljX3Fn:-KV9Lve7B1bjqW03CIkH:bmbxfyy) ([raw file](https://github.com/vaadin/maven-integration/blob/017f45dd9bb2b8141fb015042f711477328b8b73/test_archetypes.sh#L1)):_
<details><summary>

<i>Previously, Artur- (Artur) wrote…</i></summary>



> It is currently nowhere. If it is needed, it must be added somewhere
> </details>
> File can be retrieved from https://github.com/vaadin/maven-integration/blob/4bb39d2845b899e111a9ca4df3f04ea0778a8f6e/test_archetypes.sh in the future - will create an issue linking to it to get this change going forward

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-integration/6)_

**Pull request merged**
