### PR TITLE
Add api diff profile

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for flow#4419

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/maven-integration/9)

### CODE REVIEW

**Review by tsuoanttila — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/maven-integration/9)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @denis-anisimov)

___
*[parent/pom.xml, line 214 at r1](https://reviewable.io/reviews/vaadin/maven-integration/9#-LI57H2y6dwMsF2qBouv:-LI57H2y6dwMsF2qBouw:b6bdfr) ([raw file](https://github.com/vaadin/maven-integration/blob/231d3068ae1f181183a240b314e22283505f3f3c/parent/pom.xml#L214)):*
> ```XML
>         <repositories>
>             <repository>
>                 <id>vaadin-prereleases</id>
> ```

Is it really correct to provide the repository in this profile?
___
*[parent/pom.xml, line 222 at r1](https://reviewable.io/reviews/vaadin/maven-integration/9#-LI57DYE5kdhvxKK8S3O:-LI57DYE5kdhvxKK8S3P:b-k3vuq4) ([raw file](https://github.com/vaadin/maven-integration/blob/231d3068ae1f181183a240b314e22283505f3f3c/parent/pom.xml#L222)):*
> ```XML
>                 <plugin>
>                     <groupId>com.github.siom79.japicmp</groupId>
>                     <artifactId>japicmp-maven-plugin</artifactId>
> ```

missing version number for plugin.
___
*[parent/pom.xml, line 229 at r1](https://reviewable.io/reviews/vaadin/maven-integration/9#-LI56xB-1h2dXV50vI5f:-LI56xB05tQGCvdCzDmV:bxcwbst) ([raw file](https://github.com/vaadin/maven-integration/blob/231d3068ae1f181183a240b314e22283505f3f3c/parent/pom.xml#L229)):*
> ```XML
>                                 <artifactId>${project.artifactId}</artifactId>
>                                 
>                                 <version>${vaadin.api.reference.version}</version>
> ```

Could use a more common name for the reference version since this is no longer for the FW only.

**Review by denis-anisimov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/maven-integration/9)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @denis-anisimov and @tsuoanttila)

___
*[parent/pom.xml, line 214 at r1](https://reviewable.io/reviews/vaadin/maven-integration/9#-LI57H2y6dwMsF2qBouv:-LI57Xdi5PmMIpBmv6Yn:b-1wccfm) ([raw file](https://github.com/vaadin/maven-integration/blob/231d3068ae1f181183a240b314e22283505f3f3c/parent/pom.xml#L214)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Is it really correct to provide the repository in this profile?
</blockquote></details>

No idea.
Copy/paste (from FW).

Done.
___
*[parent/pom.xml, line 222 at r1](https://reviewable.io/reviews/vaadin/maven-integration/9#-LI57DYE5kdhvxKK8S3O:-LI586up7lP3BG3ShwDx:b-896fix) ([raw file](https://github.com/vaadin/maven-integration/blob/231d3068ae1f181183a240b314e22283505f3f3c/parent/pom.xml#L222)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

missing version number for plugin.
</blockquote></details>

Done.
___
*[parent/pom.xml, line 229 at r1](https://reviewable.io/reviews/vaadin/maven-integration/9#-LI56xB-1h2dXV50vI5f:-LI588vdDwQXg0p34LCh:bb5xp0b) ([raw file](https://github.com/vaadin/maven-integration/blob/231d3068ae1f181183a240b314e22283505f3f3c/parent/pom.xml#L229)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Could use a more common name for the reference version since this is no longer for the FW only.
</blockquote></details>

Hmm....
It looks quite generic for me.
Could you please suggest any example ?

**Review by tsuoanttila — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/maven-integration/9)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

___
*[parent/pom.xml, line 229 at r1](https://reviewable.io/reviews/vaadin/maven-integration/9#-LI56xB-1h2dXV50vI5f:-LI59bbw28i9HwCS3Q9X:blm835m) ([raw file](https://github.com/vaadin/maven-integration/blob/231d3068ae1f181183a240b314e22283505f3f3c/parent/pom.xml#L229)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Hmm....
It looks quite generic for me.
Could you please suggest any example ?
</blockquote></details>

`api.reference.version`. There's not really any reason to add the `vaadin.` in the front of the name.

**Review by denis-anisimov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/maven-integration/9)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @denis-anisimov)

___
*[parent/pom.xml, line 229 at r1](https://reviewable.io/reviews/vaadin/maven-integration/9#-LI56xB-1h2dXV50vI5f:-LI5AF2bDrxxw4CATLRk:b-1eh3wi) ([raw file](https://github.com/vaadin/maven-integration/blob/231d3068ae1f181183a240b314e22283505f3f3c/parent/pom.xml#L229)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

`api.reference.version`. There's not really any reason to add the `vaadin.` in the front of the name.
</blockquote></details>

Sure, done.

**Review by denis-anisimov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/maven-integration/9)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

___
*[parent/pom.xml, line 229 at r1](https://reviewable.io/reviews/vaadin/maven-integration/9#-LI56xB-1h2dXV50vI5f:-LI5ALf_2QhbZcl8ziZA:b-896fix) ([raw file](https://github.com/vaadin/maven-integration/blob/231d3068ae1f181183a240b314e22283505f3f3c/parent/pom.xml#L229)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Sure, done.
</blockquote></details>

Done.

**Review by tsuoanttila — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/maven-integration/9)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by tsuoanttila** [comment]
___
*[parent/pom.xml, line 10 at r2](https://reviewable.io/reviews/vaadin/maven-integration/9#-LI5A_UK-Dot9Fii2rtc:-LI5A_UK-Dot9Fii2rtd:b-qo1hnj) ([raw file](https://github.com/vaadin/maven-integration/blob/3c49344a44af2b407281b99dd40fcd6ad3f7514a/parent/pom.xml#L10)):*
> ```XML
>   <packaging>pom</packaging>
>   <name>Vaadin parent POM</name>
>   <version>2.0.0</version>
> ```

Hard coded version number. This might need an update..

**Review by denis-anisimov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/maven-integration/9)* status: all files reviewed, 1 unresolved discussion (waiting on @denis-anisimov)

___
*[parent/pom.xml, line 10 at r2](https://reviewable.io/reviews/vaadin/maven-integration/9#-LI5A_UK-Dot9Fii2rtc:-LI5EEy26CZEMnXyxtgo:b-y20w0t) ([raw file](https://github.com/vaadin/maven-integration/blob/3c49344a44af2b407281b99dd40fcd6ad3f7514a/parent/pom.xml#L10)):*
<details><summary><i>Previously, tsuoanttila (Teemu Suo-Anttila) wrote…</i></summary><blockquote>

Hard coded version number. This might need an update..
</blockquote></details>

`2.0.1` ?

**Review by denis-anisimov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/maven-integration/9)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @tsuoanttila)

___
*[parent/pom.xml, line 10 at r2](https://reviewable.io/reviews/vaadin/maven-integration/9#-LI5A_UK-Dot9Fii2rtc:-LI5FRY9CwzVg8n69q3R:b-896fix) ([raw file](https://github.com/vaadin/maven-integration/blob/3c49344a44af2b407281b99dd40fcd6ad3f7514a/parent/pom.xml#L10)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

`2.0.1` ?
</blockquote></details>

Done.

**Review by tsuoanttila — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/maven-integration/9)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
