### PR TITLE
Update version to 8.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by Artur-**
Updated to use compatibility packages for now

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/maven-integration/3)

### CODE REVIEW

**Comment by hesara** [comment]
Reviewed 16 of 28 files at r1.
Review status: 16 of 28 files reviewed at latest revision, 9 unresolved discussions.

---

_[archetypes/vaadin-archetype-application-example/src/main/resources/archetype-resources/**rootArtifactId**-ui/src/main/java/samples/ErrorView.java, line 8 [r1]](https://reviewable.io:443/reviews/vaadin/maven-integration/3#-KRD63dpPoZvm2ZTrzyc:-KRD63dpPoZvm2ZTrzyd:bwj0dqn) ([raw file](https://github.com/vaadin/maven-integration/blob/fd3bb2b118edd005a942aadd5e07eb967041a29c/archetypes/vaadin-archetype-application-example/src/main/resources/archetype-resources/__rootArtifactId__-ui/src/main/java/samples/ErrorView.java#L8)):_

> ``` Java
> import com.vaadin.navigator.View;
> import com.vaadin.navigator.ViewChangeListener;
> import com.vaadin.v7.ui.Label;
> ```

this could also use the new Label

---

_[archetypes/vaadin-archetype-application-example/src/main/resources/archetype-resources/**rootArtifactId**-ui/src/main/java/samples/Menu.java, line 23 [r1]](https://reviewable.io:443/reviews/vaadin/maven-integration/3#-KRD6N5yhfktgEp69uk4:-KRD6N5yhfktgEp69uk5:bwj0dqn) ([raw file](https://github.com/vaadin/maven-integration/blob/fd3bb2b118edd005a942aadd5e07eb967041a29c/archetypes/vaadin-archetype-application-example/src/main/resources/archetype-resources/__rootArtifactId__-ui/src/main/java/samples/Menu.java#L23)):_

> ``` Java
> import com.vaadin.ui.HorizontalLayout;
> import com.vaadin.ui.Image;
> import com.vaadin.v7.ui.Label;
> ```

this could also use the new Label

---

_[archetypes/vaadin-archetype-application-example/src/main/resources/archetype-resources/**rootArtifactId**-ui/src/main/java/samples/about/AboutView.java, line 13 [r1]](https://reviewable.io:443/reviews/vaadin/maven-integration/3#-KRD6YNChQgeSpIWwP5m:-KRD6YNChQgeSpIWwP5n:bz812ki) ([raw file](https://github.com/vaadin/maven-integration/blob/fd3bb2b118edd005a942aadd5e07eb967041a29c/archetypes/vaadin-archetype-application-example/src/main/resources/archetype-resources/__rootArtifactId__-ui/src/main/java/samples/about/AboutView.java#L13)):_

> ``` Java
> import com.vaadin.ui.Alignment;
> import com.vaadin.ui.CustomLayout;
> import com.vaadin.v7.ui.Label;
> ```

this could also use the new Label and ContentMode

---

_[archetypes/vaadin-archetype-application-example/src/main/resources/archetype-resources/**rootArtifactId**-ui/src/main/java/samples/authentication/LoginScreen.java, line 10 [r1]](https://reviewable.io:443/reviews/vaadin/maven-integration/3#-KRD6qQlWt9NkU3fJYxE:-KRD6qQlWt9NkU3fJYxF:b-i889qy) ([raw file](https://github.com/vaadin/maven-integration/blob/fd3bb2b118edd005a942aadd5e07eb967041a29c/archetypes/vaadin-archetype-application-example/src/main/resources/archetype-resources/__rootArtifactId__-ui/src/main/java/samples/authentication/LoginScreen.java#L10)):_

> ``` Java
> import com.vaadin.event.ShortcutAction;
> import com.vaadin.server.Page;
> import com.vaadin.v7.shared.ui.label.ContentMode;
> ```

this screen is probably easy to migrate

---

_[archetypes/vaadin-archetype-application-example/src/main/resources/archetype-resources/**rootArtifactId**-widgetset/src/main/java/client/samples/ResetButtonForTextFieldConnector.java, line 17 [r1]](https://reviewable.io:443/reviews/vaadin/maven-integration/3#-KRD7XBVtwimy3VaiApw:-KRD7XBVtwimy3VaiApx:bqizz87) ([raw file](https://github.com/vaadin/maven-integration/blob/fd3bb2b118edd005a942aadd5e07eb967041a29c/archetypes/vaadin-archetype-application-example/src/main/resources/archetype-resources/__rootArtifactId__-widgetset/src/main/java/client/samples/ResetButtonForTextFieldConnector.java#L17)):_

> ``` Java
> import com.vaadin.client.communication.StateChangeEvent;
> import com.vaadin.client.extensions.AbstractExtensionConnector;
> import com.vaadin.client.ui.VTextField;
> ```

not the v7 classes, whereas the server side uses v7

---

_[archetypes/vaadin-archetype-application-example/src/main/resources/archetype-resources/**rootArtifactId**-widgetset/src/main/java/samples/AttributeExtension.java, line 8 [r1]](https://reviewable.io:443/reviews/vaadin/maven-integration/3#-KRD7bzJ-mAlxybNiUcw:-KRD7bzJ-mAlxybNiUcx:b-z9s25q) ([raw file](https://github.com/vaadin/maven-integration/blob/fd3bb2b118edd005a942aadd5e07eb967041a29c/archetypes/vaadin-archetype-application-example/src/main/resources/archetype-resources/__rootArtifactId__-widgetset/src/main/java/samples/AttributeExtension.java#L8)):_

> ``` Java
> import com.vaadin.annotations.JavaScript;
> import com.vaadin.server.AbstractJavaScriptExtension;
> import com.vaadin.v7.ui.TextField;
> ```

(should this be for v7 text fields or v8?)

---

_[archetypes/vaadin-archetype-jee-application/pom.xml, line 14 [r1]](https://reviewable.io:443/reviews/vaadin/maven-integration/3#-KRD7vWEmQfdWBZIekzg:-KRD7vWEmQfdWBZIekzh:b5oyker) ([raw file](https://github.com/vaadin/maven-integration/blob/fd3bb2b118edd005a942aadd5e07eb967041a29c/archetypes/vaadin-archetype-jee-application/pom.xml#L14)):_

> ``` XML
>     <groupId>com.vaadin</groupId>
>     <artifactId>vaadin-archetype-java-ee-application</artifactId>
>     <version>8.0-SNAPSHOT</version>
> ```

(not built with the others for new framework versions at the moment)

---

_[archetypes/vaadin-archetype-liferay-portlet-sharedlib/pom.xml, line 13 [r1]](https://reviewable.io:443/reviews/vaadin/maven-integration/3#-KRD839AjRDenCMrm1Ng:-KRD839AjRDenCMrm1Nh:b-bqox0l) ([raw file](https://github.com/vaadin/maven-integration/blob/fd3bb2b118edd005a942aadd5e07eb967041a29c/archetypes/vaadin-archetype-liferay-portlet-sharedlib/pom.xml#L13)):_

> ``` XML
>   <groupId>com.vaadin</groupId>
>   <artifactId>vaadin-archetype-liferay-portlet-sharedlib</artifactId>
>   <version>8.0-SNAPSHOT</version>
> ```

(not built with the framework at the moment IIRC)

---

_[archetypes/vaadin-archetype-touchkit/pom.xml, line 15 [r1]](https://reviewable.io:443/reviews/vaadin/maven-integration/3#-KRD8GG94roRgeU26xqO:-KRD8GGACu4_QiYjGUBW:bek4x55) ([raw file](https://github.com/vaadin/maven-integration/blob/fd3bb2b118edd005a942aadd5e07eb967041a29c/archetypes/vaadin-archetype-touchkit/pom.xml#L15)):_

> ``` XML
>     <packaging>maven-archetype</packaging>
>     <name>Vaadin TouchKit Application Archetype</name>
>     <version>8.0-SNAPSHOT</version>
> ```

(not built with the framework at the moment, managed by the Pro team separately)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-integration/3)_

**Comment by Artur-** [comment]
Review status: 16 of 29 files reviewed at latest revision, 4 unresolved discussions.

---

_[archetypes/vaadin-archetype-application-example/src/main/resources/archetype-resources/**rootArtifactId**-widgetset/src/main/java/client/samples/ResetButtonForTextFieldConnector.java, line 17 [r1]](https://reviewable.io:443/reviews/vaadin/maven-integration/3#-KRD7XBVtwimy3VaiApw:-KRDIjN0P3nlG0jrYHF2:b-896fix) ([raw file](https://github.com/vaadin/maven-integration/blob/fd3bb2b118edd005a942aadd5e07eb967041a29c/archetypes/vaadin-archetype-application-example/src/main/resources/archetype-resources/__rootArtifactId__-widgetset/src/main/java/client/samples/ResetButtonForTextFieldConnector.java#L17)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> not the v7 classes, whereas the server side uses v7
> </details>
> Done.

---

_[archetypes/vaadin-archetype-application-example/src/main/resources/archetype-resources/**rootArtifactId**-widgetset/src/main/java/samples/AttributeExtension.java, line 8 [r1]](https://reviewable.io:443/reviews/vaadin/maven-integration/3#-KRD7bzJ-mAlxybNiUcw:-KRDIsLvxHUpJ94JgJYC:b-ogt4ae) ([raw file](https://github.com/vaadin/maven-integration/blob/fd3bb2b118edd005a942aadd5e07eb967041a29c/archetypes/vaadin-archetype-application-example/src/main/resources/archetype-resources/__rootArtifactId__-widgetset/src/main/java/samples/AttributeExtension.java#L8)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> (should this be for v7 text fields or v8?)
> </details>
> Let's tune stuff in #4 

---

_[archetypes/vaadin-archetype-liferay-portlet-sharedlib/pom.xml, line 13 [r1]](https://reviewable.io:443/reviews/vaadin/maven-integration/3#-KRD839AjRDenCMrm1Ng:-KRDJ4Up-jgrynPP9zlR:b32wtd) ([raw file](https://github.com/vaadin/maven-integration/blob/fd3bb2b118edd005a942aadd5e07eb967041a29c/archetypes/vaadin-archetype-liferay-portlet-sharedlib/pom.xml#L13)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> (not built with the framework at the moment IIRC)
> </details>
> ok

---

_[archetypes/vaadin-archetype-touchkit/pom.xml, line 15 [r1]](https://reviewable.io:443/reviews/vaadin/maven-integration/3#-KRD8GG94roRgeU26xqO:-KRDJ3yU7XJegkYDo5MW:b32wtd) ([raw file](https://github.com/vaadin/maven-integration/blob/fd3bb2b118edd005a942aadd5e07eb967041a29c/archetypes/vaadin-archetype-touchkit/pom.xml#L15)):_
<details><summary>

<i>Previously, hesara (Henri Sara) wrote…</i></summary>



> (not built with the framework at the moment, managed by the Pro team separately)
> </details>
> ok

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-integration/3)_

**Comment by hesara** [comment]
Further migration can be done later

---

Reviewed 2 of 2 files at r2.
Review status: 18 of 29 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-integration/3#-:-KRDSnoqYnnZrxqMsfCN:b-qx5vco)_

**Comment by hesara** [comment]
Reviewed 11 of 28 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/maven-integration/3)_

**Pull request merged**
